"""added is_deleted in enquiry

Revision ID: 55fd6eb9989e
Revises: 55a16c851dc6
Create Date: 2026-07-04 12:18:12.313475

"""
from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op


revision: str = '55fd6eb9989e'
down_revision: str | None = '55a16c851dc6'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('enquiries', sa.Column('is_deleted', sa.Boolean(), server_default='false', nullable=False))
    op.add_column('enquiries', sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('enquiries', 'deleted_at')
    op.drop_column('enquiries', 'is_deleted')
    # ### end Alembic commands ###
