"""added file_name column in attachments table

Revision ID: 18bce7b8538b
Revises: 182d3943b644
Create Date: 2026-07-14 15:50:34.073796

"""
from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op


revision: str = '18bce7b8538b'
down_revision: str | None = '182d3943b644'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('attachments', sa.Column('file_name', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('attachments', 'file_name')
    # ### end Alembic commands ###
