"""added new status waiting client in sitevist

Revision ID: 13ca7224954d
Revises: 6b6fdfd24087
Create Date: 2026-08-03 16:50:01.606601

"""
from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op


revision: str = '13ca7224954d'
down_revision: str | None = '6b6fdfd24087'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("ALTER TYPE sitevisitstatus ADD VALUE IF NOT EXISTS 'waiting_client'")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
