"""added enquiry and other tables

Revision ID: 55a16c851dc6
Revises: 019f31ed261d
Create Date: 2026-07-04 10:17:53.516795

"""
from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op


revision: str = '55a16c851dc6'
down_revision: str | None = '019f31ed261d'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('clients',
    sa.Column('client_name', sa.String(length=255), nullable=False),
    sa.Column('client_contact', sa.String(length=50), nullable=True),
    sa.Column('alternate_contact', sa.String(length=50), nullable=True),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('client_designation', sa.String(length=255), nullable=True),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_clients'))
    )
    op.create_table('company',
    sa.Column('company_name', sa.String(length=255), nullable=False),
    sa.Column('company_website', sa.String(length=255), nullable=True),
    sa.Column('address_line1', sa.String(length=255), nullable=True),
    sa.Column('address_line2', sa.String(length=255), nullable=True),
    sa.Column('city', sa.String(length=100), nullable=True),
    sa.Column('state', sa.String(length=100), nullable=True),
    sa.Column('country', sa.String(length=100), nullable=True),
    sa.Column('pincode', sa.String(length=20), nullable=True),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_company'))
    )
    op.create_table('project_type',
    sa.Column('type_name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.String(length=500), nullable=True),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_project_type')),
    sa.UniqueConstraint('type_name', name=op.f('uq_project_type_type_name'))
    )
    op.create_table('projects',
    sa.Column('project_name', sa.String(length=255), nullable=False),
    sa.Column('project_type_id', sa.UUID(), nullable=False),
    sa.Column('project_location', sa.String(length=255), nullable=True),
    sa.Column('estimated_budget', sa.Numeric(precision=12, scale=3), nullable=True),
    sa.Column('expected_start_date', sa.Date(), nullable=True),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['project_type_id'], ['project_type.id'], name=op.f('fk_projects_project_type_id_project_type')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_projects'))
    )
    op.create_table('enquiries',
    sa.Column('enquiry_number', sa.String(length=50), nullable=False),
    sa.Column('enquiry_date', sa.Date(), nullable=False),
    sa.Column('company_id', sa.UUID(), nullable=False),
    sa.Column('client_id', sa.UUID(), nullable=False),
    sa.Column('project_id', sa.UUID(), nullable=True),
    sa.Column('enquiry_source', sa.Enum('email', 'whatsapp', 'instagram', 'facebook', 'linkedin', 'website', 'direct_call', 'referral', 'tender', 'other', name='enquirysource'), nullable=True),
    sa.Column('priority', sa.Enum('low', 'medium', 'high', name='enquirypriority'), nullable=False),
    sa.Column('status', sa.Enum('enquiry', 'site_visit', 'quotation', 'accepted', 'lost', name='enquirystatus'), nullable=False),
    sa.Column('sales_executive_id', sa.UUID(), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('remarks', sa.Text(), nullable=True),
    sa.Column('stage_lost', sa.String(length=100), nullable=True),
    sa.Column('lost_reason', sa.String(length=500), nullable=True),
    sa.Column('date_lost', sa.Date(), nullable=True),
    sa.Column('follow_up_date', sa.Date(), nullable=True),
    sa.Column('reinstated', sa.Boolean(), nullable=False),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['client_id'], ['clients.id'], name=op.f('fk_enquiries_client_id_clients')),
    sa.ForeignKeyConstraint(['company_id'], ['company.id'], name=op.f('fk_enquiries_company_id_company')),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], name=op.f('fk_enquiries_project_id_projects')),
    sa.ForeignKeyConstraint(['sales_executive_id'], ['users.id'], name=op.f('fk_enquiries_sales_executive_id_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_enquiries')),
    sa.UniqueConstraint('enquiry_number', name=op.f('uq_enquiries_enquiry_number'))
    )
    op.create_table('quotations',
    sa.Column('quotation_number', sa.String(length=50), nullable=False),
    sa.Column('enquiry_id', sa.UUID(), nullable=False),
    sa.Column('company_id', sa.UUID(), nullable=False),
    sa.Column('executive_id', sa.UUID(), nullable=True),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('is_current', sa.Boolean(), nullable=False),
    sa.Column('amount', sa.Numeric(precision=12, scale=3), nullable=True),
    sa.Column('currency', sa.String(length=10), nullable=False),
    sa.Column('sent_date', sa.Date(), nullable=True),
    sa.Column('status', sa.Enum('draft', 'sent', 'accepted', 'rejected', name='quotationstatus'), nullable=False),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['company.id'], name=op.f('fk_quotations_company_id_company')),
    sa.ForeignKeyConstraint(['enquiry_id'], ['enquiries.id'], name=op.f('fk_quotations_enquiry_id_enquiries')),
    sa.ForeignKeyConstraint(['executive_id'], ['users.id'], name=op.f('fk_quotations_executive_id_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_quotations')),
    sa.UniqueConstraint('quotation_number', name=op.f('uq_quotations_quotation_number'))
    )
    op.create_table('site_visits',
    sa.Column('visit_number', sa.String(length=50), nullable=False),
    sa.Column('enquiry_id', sa.UUID(), nullable=False),
    sa.Column('company_id', sa.UUID(), nullable=False),
    sa.Column('engineer_id', sa.UUID(), nullable=True),
    sa.Column('sales_executive_id', sa.UUID(), nullable=True),
    sa.Column('visit_date', sa.DateTime(timezone=True), nullable=False),
    sa.Column('status', sa.Enum('scheduled', 'completed', 'cancelled', name='sitevisitstatus'), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['company.id'], name=op.f('fk_site_visits_company_id_company')),
    sa.ForeignKeyConstraint(['engineer_id'], ['users.id'], name=op.f('fk_site_visits_engineer_id_users')),
    sa.ForeignKeyConstraint(['enquiry_id'], ['enquiries.id'], name=op.f('fk_site_visits_enquiry_id_enquiries')),
    sa.ForeignKeyConstraint(['sales_executive_id'], ['users.id'], name=op.f('fk_site_visits_sales_executive_id_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_site_visits')),
    sa.UniqueConstraint('visit_number', name=op.f('uq_site_visits_visit_number'))
    )
    op.create_table('attachments',
    sa.Column('file', sa.String(length=255), nullable=False),
    sa.Column('file_type', sa.String(length=100), nullable=True),
    sa.Column('document_type', sa.Enum('boq', 'drawings', 'photos', 'tender', 'other', name='attachmentdocumenttype'), nullable=True),
    sa.Column('uploaded_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('enquiry_id', sa.UUID(), nullable=True),
    sa.Column('site_visit_id', sa.UUID(), nullable=True),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.ForeignKeyConstraint(['enquiry_id'], ['enquiries.id'], name=op.f('fk_attachments_enquiry_id_enquiries')),
    sa.ForeignKeyConstraint(['site_visit_id'], ['site_visits.id'], name=op.f('fk_attachments_site_visit_id_site_visits')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_attachments'))
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('attachments')
    op.drop_table('site_visits')
    op.drop_table('quotations')
    op.drop_table('enquiries')
    op.drop_table('projects')
    op.drop_table('project_type')
    op.drop_table('company')
    op.drop_table('clients')
    # ### end Alembic commands ###
