"""added new map_link column

Revision ID: 3b1275801282
Revises: 76ff5e19851b
Create Date: 2026-08-12 16:39:25.165302

"""
from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op


revision: str = '3b1275801282'
down_revision: str | None = '76ff5e19851b'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('site_visits', sa.Column('map_link', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('site_visits', 'map_link')
    # ### end Alembic commands ###
