"""added quotation junction table

Revision ID: 1f43c38b2014
Revises: 3a0f64cc77b8
Create Date: 2026-08-05 17:09:40.729982

"""
from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op


revision: str = '1f43c38b2014'
down_revision: str | None = '3a0f64cc77b8'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('quotation_signatures',
    sa.Column('quotation_id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['quotation_id'], ['quotations.id'], name=op.f('fk_quotation_signatures_quotation_id_quotations'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_quotation_signatures_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('quotation_id', 'user_id', name=op.f('pk_quotation_signatures'))
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('quotation_signatures')
    # ### end Alembic commands ###
