"""added_enquiry_audit_log_table

Revision ID: 921cd6b29d28
Revises: 037153fb7e2b
Create Date: 2026-07-12 12:46:06.013008

"""
from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op


revision: str = '921cd6b29d28'
down_revision: str | None = '037153fb7e2b'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('site_visits', sa.Column('requirements', sa.Text(), nullable=True))
    op.add_column('site_visits', sa.Column('measurements', sa.Text(), nullable=True))
    op.add_column('site_visits', sa.Column('existing_conditions', sa.Text(), nullable=True))
    op.add_column('site_visits', sa.Column('challenges', sa.Text(), nullable=True))
    op.add_column('site_visits', sa.Column('recommendation', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('site_visits', 'recommendation')
    op.drop_column('site_visits', 'challenges')
    op.drop_column('site_visits', 'existing_conditions')
    op.drop_column('site_visits', 'measurements')
    op.drop_column('site_visits', 'requirements')
    # ### end Alembic commands ###
