"""added client_rep columns and visit count in site_visit

Revision ID: 037153fb7e2b
Revises: 55fd6eb9989e
Create Date: 2026-07-11 15:42:17.944240

"""
from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op


revision: str = '037153fb7e2b'
down_revision: str | None = '55fd6eb9989e'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('site_visits', sa.Column('visit_count', sa.Integer(), nullable=False))
    op.add_column('site_visits', sa.Column('client_representative', sa.String(length=255), nullable=True))
    op.add_column('site_visits', sa.Column('client_representative_no', sa.String(length=50), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('site_visits', 'client_representative_no')
    op.drop_column('site_visits', 'client_representative')
    op.drop_column('site_visits', 'visit_count')
    # ### end Alembic commands ###
