"""added new site_address column

Revision ID: 76ff5e19851b
Revises: 0ab27dc6c623
Create Date: 2026-08-12 16:22:54.438190

"""
from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op


revision: str = '76ff5e19851b'
down_revision: str | None = '0ab27dc6c623'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.get_context().autocommit_block():
        op.execute("ALTER TYPE sitevisitstatus ADD VALUE IF NOT EXISTS 'reopened'")
    op.add_column('site_visits', sa.Column('site_address', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('site_visits', 'site_address')
    # ### end Alembic commands ###
