"""added subject and profit estimator column in quotation

Revision ID: 6b6fdfd24087
Revises: 656649d2cddd
Create Date: 2026-08-02 08:13:09.065902

"""
from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

revision: str = '6b6fdfd24087'
down_revision: str | None = '656649d2cddd'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # Add missing AttachmentDocumentType enums
    op.execute("ALTER TYPE enquiryauditaction ADD VALUE 'quotation_generated'")
    op.execute("ALTER TYPE attachmentdocumenttype ADD VALUE IF NOT EXISTS 'videos'")
    op.execute("ALTER TYPE attachmentdocumenttype ADD VALUE IF NOT EXISTS 'measurement_sheets'")
    
    op.add_column('quotation_line_items', sa.Column('profit_estimator', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    op.add_column('quotations', sa.Column('subject', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('quotations', 'subject')
    op.drop_column('quotation_line_items', 'profit_estimator')
    # ### end Alembic commands ###
