"""added is_signature column in user table

Revision ID: 182d3943b644
Revises: 921cd6b29d28
Create Date: 2026-07-12 13:21:04.672357

"""
from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op


revision: str = '182d3943b644'
down_revision: str | None = '921cd6b29d28'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('is_signature', sa.Boolean(), nullable=True))
    op.add_column('users', sa.Column('signature', sa.String(length=2048), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'signature')
    op.drop_column('users', 'is_signature')
    # ### end Alembic commands ###
