"""added is draft colummn in quotation

Revision ID: cfab24a24b12
Revises: 13ca7224954d
Create Date: 2026-08-03 17:12:12.243525

"""
from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op


revision: str = 'cfab24a24b12'
down_revision: str | None = '13ca7224954d'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("ALTER TYPE sitevisitstatus ADD VALUE IF NOT EXISTS 'enquiry_lost'")
    op.add_column('quotations', sa.Column('is_draft', sa.Boolean(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('quotations', 'is_draft')
    # ### end Alembic commands ###
