"""added new notes column in enquiry

Revision ID: 0ab27dc6c623
Revises: 1f43c38b2014
Create Date: 2026-08-12 15:08:00.207624

"""
from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op


revision: str = '0ab27dc6c623'
down_revision: str | None = '1f43c38b2014'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('enquiries', sa.Column('notes', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('enquiries', 'notes')
    # ### end Alembic commands ###
