"""fix_audit_log_timezone

Revision ID: 7d9f2d068793
Revises: bd296c84e07a
Create Date: 2026-08-02 07:07:54.944776

"""
from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

revision: str = '7d9f2d068793'
down_revision: str | None = 'bd296c84e07a'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('quotation_line_items',
    sa.Column('quotation_id', sa.UUID(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('quantity', sa.Numeric(precision=12, scale=3), nullable=False),
    sa.Column('unit', sa.String(length=50), nullable=True),
    sa.Column('rate', sa.Numeric(precision=12, scale=3), nullable=False),
    sa.Column('amount', sa.Numeric(precision=12, scale=3), nullable=False),
    sa.Column('estimated_cost', sa.Numeric(precision=12, scale=3), nullable=True),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['quotation_id'], ['quotations.id'], name=op.f('fk_quotation_line_items_quotation_id_quotations'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_quotation_line_items'))
    )
    op.alter_column('enquiry_audit_log', 'action_date',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=False)
    op.add_column('quotations', sa.Column('quotation_date', sa.Date(), nullable=True))
    op.add_column('quotations', sa.Column('valid_until', sa.Date(), nullable=True))
    op.add_column('quotations', sa.Column('site_visit_id', sa.UUID(), nullable=True))
    op.add_column('quotations', sa.Column('subtotal', sa.Numeric(precision=12, scale=3), nullable=True))
    op.add_column('quotations', sa.Column('global_discount', sa.Numeric(precision=12, scale=3), nullable=True))
    op.add_column('quotations', sa.Column('vat_rate', sa.Numeric(precision=5, scale=2), nullable=True))
    op.add_column('quotations', sa.Column('expected_profit', sa.Numeric(precision=12, scale=3), nullable=True))
    op.add_column('quotations', sa.Column('total_estimated_cost', sa.Numeric(precision=12, scale=3), nullable=True))
    op.create_foreign_key(op.f('fk_quotations_site_visit_id_site_visits'), 'quotations', 'site_visits', ['site_visit_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('fk_quotations_site_visit_id_site_visits'), 'quotations', type_='foreignkey')
    op.drop_column('quotations', 'total_estimated_cost')
    op.drop_column('quotations', 'expected_profit')
    op.drop_column('quotations', 'vat_rate')
    op.drop_column('quotations', 'global_discount')
    op.drop_column('quotations', 'subtotal')
    op.drop_column('quotations', 'site_visit_id')
    op.drop_column('quotations', 'valid_until')
    op.drop_column('quotations', 'quotation_date')
    op.alter_column('enquiry_audit_log', 'action_date',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=False)
    op.drop_table('quotation_line_items')
    # ### end Alembic commands ###
