"""missed audit log table

Revision ID: bd296c84e07a
Revises: 18bce7b8538b
Create Date: 2026-08-02 06:51:07.915819

"""
from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op


revision: str = 'bd296c84e07a'
down_revision: str | None = '18bce7b8538b'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('enquiry_audit_log',
    sa.Column('enquiry_id', sa.UUID(), nullable=False),
    sa.Column('action', sa.Enum('enquiry_created', 'site_visit_scheduled', 'enquiry_lost', 'enquiry_reinstated', name='enquiryauditaction'), nullable=False),
    sa.Column('action_date', sa.DateTime(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['enquiry_id'], ['enquiries.id'], name=op.f('fk_enquiry_audit_log_enquiry_id_enquiries'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_enquiry_audit_log'))
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('enquiry_audit_log')
    # ### end Alembic commands ###
