"""added new columns in quotation

Revision ID: 3a0f64cc77b8
Revises: cfab24a24b12
Create Date: 2026-08-05 16:02:45.525625

"""
from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op


revision: str = '3a0f64cc77b8'
down_revision: str | None = 'cfab24a24b12'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('quotations', sa.Column('version_no', sa.String(length=50), nullable=True))
    op.add_column('quotations', sa.Column('created_by_id', sa.UUID(), nullable=False))
    op.add_column('quotations', sa.Column('updated_by_id', sa.UUID(), nullable=True))
    op.create_foreign_key(op.f('fk_quotations_updated_by_id_users'), 'quotations', 'users', ['updated_by_id'], ['id'], ondelete='RESTRICT')
    op.create_foreign_key(op.f('fk_quotations_created_by_id_users'), 'quotations', 'users', ['created_by_id'], ['id'], ondelete='RESTRICT')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('fk_quotations_created_by_id_users'), 'quotations', type_='foreignkey')
    op.drop_constraint(op.f('fk_quotations_updated_by_id_users'), 'quotations', type_='foreignkey')
    op.drop_column('quotations', 'updated_by_id')
    op.drop_column('quotations', 'created_by_id')
    op.drop_column('quotations', 'version_no')
    # ### end Alembic commands ###
