"""add_phone_to_user

Revision ID: 019f31ed261d
Revises: 0008_user_image
Create Date: 2026-07-04 05:44:20.492623

"""
from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op


revision: str = '019f31ed261d'
down_revision: str | None = '0008_user_image'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('roles', 'role_code',
               existing_type=sa.TEXT(),
               type_=sa.String(length=32),
               existing_nullable=False)
    op.drop_index(op.f('idx_user_roles_role'), table_name='user_roles')
    op.add_column('users', sa.Column('phone', sa.String(length=50), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'phone')
    op.create_index(op.f('idx_user_roles_role'), 'user_roles', ['role_id'], unique=False)
    op.alter_column('roles', 'role_code',
               existing_type=sa.String(length=32),
               type_=sa.TEXT(),
               existing_nullable=False)
    # ### end Alembic commands ###
