"""added quotation generated enum

Revision ID: 656649d2cddd
Revises: 7d9f2d068793
Create Date: 2026-08-02 07:45:14.952854

"""
from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op


revision: str = '656649d2cddd'
down_revision: str | None = '7d9f2d068793'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('quotations', sa.Column('terms_and_conditions', sa.Text(), nullable=True))
    op.add_column('quotations', sa.Column('remarks', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('quotations', 'remarks')
    op.drop_column('quotations', 'terms_and_conditions')
    # ### end Alembic commands ###
